config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bills
  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	has_many :cloths, dependent: :destroy
	validates :name, presence: true
	validates :mobile, presence: true, length: {is: 10}
	validates :fare, presence: true
end

app/models/cloth.rb
class Cloth < ActiveRecord::Base
	belongs_to :bill
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
before_action :get_bill, only:[:show, :edit, :update, :destroy]

def index
	@bills = Bill.all
end

def new
	@bill = Bill.new
end

def create
	@bill = Bill.new(bill_params)
	@bill.status = "pending"
	if @bill.save
		redirect_to bills_path, notice: 'bill added successfully'
    else
    	render "new"
    end

end

def edit
	
end

def show
	
end

def update
	
end

def destroy
	
end

private

def get_bill
	@bill = Bill.find(params[:id])
end

def bill_params
	#params.require(:bill).permit(:name, :delivery_date, :fare, :advance)
	params.require(:bill).permit(:name, :mobile, :delivery_date, :fare, :advance, :status)
end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/views/bills/index.html.erb
<div class="well">
<div class="float-right">
<%= link_to '+New Bill', new_bill_path, class: 'btn btn-info'%></div>
<table class="table table-striped table-hover" >
	<thead>

	<th>Name</th>
	<th>Mobile</th>
	<th>Price</th>
	<th>Advance</th>
	<th>Status</th>
	<th>Delivery On</th>
	</thead>
	<tbody>
		<tr><%@bills.each do |bill|%></tr>
          <tr>
          	<td><%= bill.name%></td>
          	<td><%= bill.mobile%></td>
          	<td><%= bill.fare %></td>
          	<td><%= bill.advance%></td>
          	<td><%= bill.status%></td>
          	<td><%= bill.delivery_date%></td>
          </tr>
		<%end%>
	</tbody>
</table>
</div>

app/views/bills/new.html.erb
<%= simple_form_for(@bill) do |f|%>
<div class="col-md-10">
<div class="well">
<div class="container">
	<form class="form-horizontal">
	<legend>New Bill</legend>
	<div class="form-group">
        <%= f.label :name%></br>
	<%= f.text_field :name, :placeholder => 'Customer name...'%>
	</div>
	<div class="form-group">
<%= f.label :mobile%>	</br>
	<%= f.text_field :mobile, :placeholder => 'mobile'%></div>
	<div class="form-group">
<%= f.label :fare%></br>	
	<%= f.text_field :fare%></div>
	<div class="form-group">
<%= f.label :Advance%>	</br><%= f.text_field :advance%></div>
	<div class="form-group"><%= f.input :delivery_date%></div>
	<div class="form-group"><%= f.button :submit, class: 'btn btn-primary'%></div>
    
	</form>
</div>
</div>
</div>
<%end%>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Laundry</a>
      
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%if user_signed_in?%>
         <li><%= link_to 'Bills', bills_path%></li>
         <div class="nav navbar-nav navbar-right">
         <ul class="nav navbar-nav navbar-right">
           <li class="dropdown">
             <%= link_to '#', class:'dropdown-toggle', "data-toggle" => 'dropdown' do%>
             <%= current_user.email%>
              <span class = "caret"></span>
             <ul class="dropdown-menu">
               <li><%= link_to 'Edit Account', edit_user_registration_path%></li>
               <li><%= link_to "Logout", destroy_user_session_path%></li>
             </ul>
             <%end%>
           </li>
         </ul>
         </div>
        <%end%>
  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Laundry</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>

<body>
<header>
  <%= render 'layouts/navigation' %>	
</header>
    <main>
    <%= render 'layouts/messages' %>
    <%= yield %>
    </main>


</body>
</html>